SELECT DISTINCT M.NAME 
FROM MEAL M 
LEFT JOIN INGREDIENT I ON M.MEAL_ID = I.MEAL_ID;

SELECT DISTINCT M.NAME 
FROM MEAL M
RIGHT JOIN INGREDIENT I ON M.MEAL_ID = I.MEAL_ID;

SELECT DISTINCT M.NAME
FROM MEAL M 
INNER JOIN INGREDIENT I ON M.MEAL_ID = I.MEAL_ID;

SELECT DISTINCT M.NAME
FROM MEAL M 
LEFT JOIN INGREDIENT I ON M.MEAL_ID = I.MEAL_ID 
WHERE I.MEAL_ID IS NULL;

SELECT DISTINCT M.NAME 
FROM MEAL M
RIGHT JOIN INGREDIENT I ON M.MEAL_ID = I.MEAL_ID
WHERE M.MEAL_ID IS NULL;