
SELECT MEAL_NAME, COUNT (*) AS NUMBER_OF_ORDERS FROM MEAL_ORDER_WITH_DETAILS
GROUP BY MEAL_NAME;

SELECT MEAL_NAME,
SUM(PRICE) AS TOTAL_REVENUE_OF_MEALS FROM MEAL_ORDER_WITH_DETAILS
WHERE PRICE>15
GROUP BY MEAL_NAME;

SELECT COUNT(*) AS NUMBER_OF_MEALS_WITH_HIGH_CALORIES
FROM MEAL
WHERE CALORIES>500;

SELECT SUM(PRICE) AS TOTAL_PRICE_OF_MEALS_CONTAINING_S
FROM MEAL
WHERE NAME  LIKE '%s%';

SELECT NAME
FROM MEAL
WHERE LOWER(NAME) LIKE '%s%';

SELECT MEAL_NAME, COUNT(*)
FROM MEAL_ORDER_WITH_DETAILS
WHERE TIME_MEAL_ORDERED < "2023-06-07 12:00:00"
GROUP BY MEAL_NAME;

