
SELECT DISTINCT M.NAME AS MEALS 
FROM MEAL M
JOIN INGREDIENT I ON M.MEAL_ID = I.MEAL_ID
WHERE I.NAME = 'Garlic';

SELECT COUNT(DISTINCT M.MEAL_ID) AS NUMBER_OF_VEGETARIAN_MEALS 
FROM MEAL M
JOIN INGREDIENT I ON M.MEAL_ID = I.MEAL_ID
WHERE I.VEGETARIAN = TRUE;

SELECT DISTINCT M.NAME
FROM MEAL M
JOIN INGREDIENT I ON M.MEAL_ID = I.MEAL_ID
WHERE VEGAN = TRUE AND GLUTEN_FREE = TRUE;

SELECT M.NAME, COUNT(*) AS NUMBER_OF_INGREDIENT 
FROM MEAL M
JOIN INGREDIENT I ON I.MEAL_ID = M.MEAL_ID
GROUP BY M.NAME;

SELECT DISTINCT M.NAME AS MEALS_WITH_MORE_THAN_3_INGREDIENT 
FROM MEAL M
JOIN INGREDIENT I ON M.MEAL_ID = I.MEAL_ID
GROUP BY M.NAME
HAVING COUNT(I.NAME)>3;

SELECT * FROM CUSTOMER C INNER 
JOIN O ON C.CUSTOMER_ID = O.CUSTOMER_ID;

SELECT * FROM INVENTORY I INNER 
JOIN P ON I.PRODUCT_ID = P.PRODUCT_ID;