SELECT MAX (PRICE) 
FROM MEAL WHERE CALORIES>500;

SELECT AVG (CALORIES)
FROM MEAL WHERE PRICE>15;

SELECT NAME, PRICE FROM MEAL GROUP BY NAME, HAVING PRICE = (SELECT MAX(PRICE) FROM MEAL);

SELECT NAME, PRICE FROM MEAL GROUP BY NAME, HAVING PRICE < (SELECT AVG(PRICE) FROM MEAL);

SELECT NAME, PRICE FROM MEAL GROUP BY NAME, HAVING PRICE < (SELECT AVG(PRICE) FROM MEAL) AND MAX(CALORIES)>600;